//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Greg.RestLearning.ServiceClient.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IRestFeedService1")]
    public interface IRestFeedService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestFeedService1/RssFeed", ReplyAction="http://tempuri.org/IRestFeedService1/RssFeedResponse")]
        System.ServiceModel.Syndication.Rss20FeedFormatter RssFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestFeedService1/AtomFeed", ReplyAction="http://tempuri.org/IRestFeedService1/AtomFeedResponse")]
        System.ServiceModel.Syndication.Atom10FeedFormatter AtomFeed();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRestFeedService1/Test", ReplyAction="http://tempuri.org/IRestFeedService1/TestResponse")]
        string Test();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRestFeedService1Channel : Greg.RestLearning.ServiceClient.ServiceReference1.IRestFeedService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RestFeedService1Client : System.ServiceModel.ClientBase<Greg.RestLearning.ServiceClient.ServiceReference1.IRestFeedService1>, Greg.RestLearning.ServiceClient.ServiceReference1.IRestFeedService1 {
        
        public RestFeedService1Client() {
        }
        
        public RestFeedService1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RestFeedService1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestFeedService1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RestFeedService1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.ServiceModel.Syndication.Rss20FeedFormatter RssFeed() {
            return base.Channel.RssFeed();
        }
        
        public System.ServiceModel.Syndication.Atom10FeedFormatter AtomFeed() {
            return base.Channel.AtomFeed();
        }
        
        public string Test() {
            return base.Channel.Test();
        }
    }
}
